In [1]:
import torch
import torch.nn.functional as F

input_tensor = torch.tensor([
    [1.0, 0.5, 0.3],
    [0.2, 0.1, 0.7],
    [0.4, 0.8, 0.6]
])  

W_Q = torch.rand(3, 3)
W_K = torch.rand(3, 3)
W_V = torch.rand(3, 3)

Q = input_tensor @ W_Q 
K = input_tensor @ W_K
V = input_tensor @ W_V

d_k = K.shape[-1]
attention_scores = Q @ K.T / torch.sqrt(torch.tensor(d_k, dtype=torch.float32))

attention_weights = F.softmax(attention_scores, dim=-1)

output = attention_weights @ V

print("Attention Scores:\n", attention_scores)
print("Attention Weights (after softmax):\n", attention_weights)
print("Output after Self-Attention:\n", output)


Attention Scores:
 tensor([[1.4079, 0.5705, 1.3870],
        [0.7807, 0.3727, 0.7872],
        [1.2414, 0.5781, 1.2422]])
Attention Weights (after softmax):
 tensor([[0.4146, 0.1794, 0.4060],
        [0.3743, 0.2489, 0.3768],
        [0.3975, 0.2048, 0.3978]])
Output after Self-Attention:
 tensor([[1.1806, 0.7543, 0.6729],
        [1.1221, 0.7147, 0.6509],
        [1.1588, 0.7401, 0.6656]])
